### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by the4anoni** [antlafarge/jdownloader#1]
Hi
Just wanted to say that antlafarge/jdownloader:latest Arm64 works much better than Jaymoulin container ;)

**Comment by antlafarge** [comment]
Hello, That's great to hear it.
Thank you so much, I needed some feedback on arm64 arch ;)
Do not hesitate to let me know if you see things to improve!

**Comment by antlafarge** [comment]
Have you tested the ubuntu and/or the alpine version?

**Comment by the4anoni** [comment]
> Have you tested the ubuntu and/or the alpine version?
> (latest is ubuntu)

Ubuntu

**Comment by antlafarge** [comment]
Ok thank you! Can I mention in the readme you tested ubuntu on the arm64 arch? :)

**Comment by the4anoni** [comment]
> Ok thank you! Can I mention in the readme you tested ubuntu on the arm64 arch? :)

Yes

**Comment by antlafarge** [comment]
Ok thank you so much for taking time for the feedback!

**Comment by the4anoni** [comment]
Do you know why JDownloader changes owner of downloads folder? I can't access it via Samba :(

**Comment by antlafarge** [comment]
If you didn't set UID and GID when you started the container, the container uses 1000 as UID and GID.
To know what UID and GID you need to use, you can use these commands :
UID : `id -u myUserName`
GID : `cut -d: -f3 < <(getent group myUserName)`
And the folder and files will be created with this user as user owner and group owner.

**Comment by antlafarge** [comment]
Did you manage to use the container with the correct UID and GID?

**Comment by the4anoni** [comment]
> Did you manage to use the container with the correct UID and GID?

Yes, thanks.

**Comment by antlafarge** [comment]
Okay great! I will add some comments in the README because I think it is not clear :)

**Comment by the4anoni** [comment]
> If you didn't set UID and GID when you started the container, the container uses 1000 as UID and GID.
> To know what UID and GID you need to use when running the container, you can use these commands :
> UID : `id -u myUserName`
> GID : `cut -d: -f3 < <(getent group myUserNameOrGroupName)`
> And the folder and files will be created with this user as user owner and group owner.

Didn't worked for me
My docker compose:
```version: '2'
services:
  jdownloader:
    image: antlafarge/jdownloader:latest
    container_name: jdownloader
    restart: on-failure:2
    volumes:
      - "/srv/dev-disk-by-uuid-4c2da230-cb59-433b-bd45-e803300590cc/Pobrane:/jdownloader/downloads"
      - "/srv/docker/jdownloader/cfg:/jdownloader/cfg"
      - "/srv/docker/jdownloader/logs:/jdownloader/logs"
    environment:
      - "JD_EMAIL=mymail@gmail.com"
      - "JD_PASSWORD=MySuperUberHardPassword"
      - "JD_NAME=MalinaPi4"
      - "UID=1001"
      - "GID=100"
    ports:
      - "3129:3129"```

Container doesnt start
```2021-04-30T11:38:19+00:00| ================================ CONTAINER STARTED ================================


2021-04-30T11:38:19+00:00| Setting up User and Group


2021-04-30T11:38:19+00:00| UID or GID does not match (currentUID='', UID='1001', currentGID='', GID='100')


2021-04-30T11:38:19+00:00| Create group with GID '100'


groupadd: GID '100' already exists


2021-04-30T11:38:19+00:00| Create user with UID '1001'


useradd: group 'jdgroup' does not exist


2021-04-30T11:38:19+00:00| User and group set up


2021-04-30T11:38:19+00:00| ----------------------------------------


2021-04-30T11:38:19+00:00| Setting up JDownloader


2021-04-30T11:38:19+00:00| Replacing JDownloader email in myJDownloader settings file


2021-04-30T11:38:19+00:00| Replacing JDownloader password in myJDownloader settings file


2021-04-30T11:38:19+00:00| Replacing JDownloader devicename in myJDownloader settings file


2021-04-30T11:38:19+00:00| JDownloader set up


2021-04-30T11:38:19+00:00| ----------------------------------------


2021-04-30T11:38:19+00:00| Downloading JDownloader.jar


2021-04-30T11:38:19+00:00| JDownloader.jar downloaded


2021-04-30T11:38:20+00:00| Setup access rights to current directory


chown: invalid user: ‘jduser:jdgroup’


2021-04-30T11:38:20+00:00| ----------------------------------------


2021-04-30T11:38:20+00:00| Starting JDownloader


su: user jduser does not exist


2021-04-30T11:38:20+00:00| JDownloader stopped


2021-04-30T11:38:20+00:00| ================================ CONTAINER STOPPED ================================```

**Comment by antlafarge** [comment]
Ok I see, You are using the group GID 100. Custom users and groups uses generaly IDs greater than or equal to 1000. What is the name and the purpose of this group on your machine? I need to understand what you tried to do to reproduce this problem :)

**Comment by the4anoni** [comment]
> Ok I see, You are using the group GID 100. Custom users and groups uses generaly IDs greater than or equal to 1000. What is the name and the purpose of this group on your machine? I need to understand what you tried to do to reproduce this problem :)

This is users group.

`filip@MalinaPi4:~$ id                                                           uid=1001(filip) gid=100(users) groups=100(users),0(root),4(adm),27(sudo),111(ssh)`

**Comment by antlafarge** [comment]
Ok I worked on the support of this group. I pushed a new image with a fix.
Can you try again and tell me if it works with the `users` GID now?

**Comment by the4anoni** [comment]
> Ok I worked on the support of this group. I pushed a new image with a fix.
> Can you try again and tell me if it works now with the `users` GID?

It looks like it works now  :)
`2021-05-04T07:45:06+00:00| ======================================== CONTAINER STARTED =========================================


2021-05-04T07:45:06+00:00| Setting up User and Group


2021-05-04T07:45:06+00:00| Create user 'jduser' (UID '1001') with primary group 'users' (GID '100')


./docker-entrypoint.sh: line 81: [: missing `]'


./docker-entrypoint.sh: line 81: -z: command not found


2021-05-04T07:45:06+00:00| ----------------------------------------


2021-05-04T07:45:06+00:00| Setting up JDownloader


2021-05-04T07:45:06+00:00| Replacing JDownloader email in myJDownloader settings file


2021-05-04T07:45:06+00:00| Replacing JDownloader password in myJDownloader settings file


2021-05-04T07:45:06+00:00| Replacing JDownloader devicename in myJDownloader settings file


2021-05-04T07:45:06+00:00| JDownloader set up


2021-05-04T07:45:06+00:00| ----------------------------------------


2021-05-04T07:45:06+00:00| Downloading JDownloader.jar


2021-05-04T07:45:07+00:00| JDownloader.jar downloaded


2021-05-04T07:45:07+00:00| Setup access rights to current directory


2021-05-04T07:45:07+00:00| ----------------------------------------


2021-05-04T07:45:07+00:00| Starting JDownloader


2021-05-04T07:45:07+00:00| JDownloader started (PID 76)`

**Comment by antlafarge** [comment]
I saw there was a bug in your logs so I fixed this.

I don't know Stack. Can you explain precisely what it is and how you use it please?
(I will do some tests by my side)

**Comment by the4anoni** [comment]
> I saw there was a bug in your logs so I fixed it (I published a new image).
> 
> I don't know Stack.
> Can you explain to me exactly what it is and how to use it please?
> I will do some tests by my side if I can.

https://prnt.sc/12ipzrf
This is where I am adding Docker-compose

**Comment by the4anoni** [comment]
> Do you have the same issue without using this management tool?

Yes

**Comment by antlafarge** [comment]
Can you explain what you are trying to do? What do you expect? And what is the current behavior?
Thank you!

**Comment by the4anoni** [comment]
> Can you explain what you are trying to do? (the steps to reproduce)
> What do you expect?
> And what is the current behavior?
> Thank you!
> 
> NB: I just fixed an issue in the users checkup on container restart.

When I install extension from here
![image](https://user-images.githubusercontent.com/13403084/119218543-1f45ad00-bae1-11eb-8991-610fdc3155ad.png)
After restarting container extensions are gone.

**Comment by antlafarge** [comment]
Ok you spoke about extensions (plugins are something else).
I tried and it works well by my side on my raspberry pi 3 (running arm64 image), and on my desktop computer (running amd64 image).
Are you sure you let enough time to jdownloader to download and install the extensions before restarting the container?

**Comment by the4anoni** [comment]
Hmm, maybe my bad.
I've setuped container again, and installed one addon by time.
Seems it works ok now.

**Comment by antlafarge** [comment]
Okay great !
No problem sounds good it works now :)

**Comment by antlafarge** [comment]
Please let me know what is your device ? And what is your OS? :)

**Comment by the4anoni** [comment]
> Please let me know what is your device ? And what is your OS? :)

Raspbian Lite Arm64

**Comment by antlafarge** [comment]
On a Raspberry PI 4B ?

**Comment by the4anoni** [comment]
> On a Raspberry PI 4B ?

Yes, 4B 4GB

**Comment by antlafarge** [comment]
OK thank you! :)

**Comment by the4anoni** [comment]
> > Can you explain what you are trying to do? (the steps to reproduce)
> > What do you expect?
> > And what is the current behavior?
> > Thank you!
> > NB: I just fixed an issue in the users checkup on container restart.
> 
> When I install extension from here
> ![image](https://user-images.githubusercontent.com/13403084/119218543-1f45ad00-bae1-11eb-8991-610fdc3155ad.png)
> After restarting container extensions are gone.

The problem still exists.

**Comment by antlafarge** [comment]
![image](https://user-images.githubusercontent.com/2077556/124536972-477f3600-de19-11eb-8a4c-01eaec6f89c0.png)

I tested it by my side on my Raspberry PI 4B (running raspberry os arm64), and I managed to install the extensions.

**Comment by antlafarge** [comment]
Anyway if you encounter problems to install the extensions, I don't think I am the best person to help you. Maybe you should contact the official JDownloader support?

**Comment by the4anoni** [comment]
> Anyway if you encounter problems to install the extensions, I don't think I am the best person to help you. Maybe you should contact the official JDownloader support?

Everything works fine If I install them on non-docker JDownloader.

**Comment by antlafarge** [comment]
As shown, by my side it works well in a docker container.
The only thing we can check is the directories permissions. If everything is OK, this is an issue in JDownloader side, and you should contact the JDownloader support.
I recommend to do a fresh install, try to install the extensions, and share the generated JDownloader logs to the JDownloader support : support@jdownloader.org
