### ISSUE TITLE
Download JDownloader.jar failed

### ISSUE THREAD

**Issue by RdTrxx** [antlafarge/jdownloader#15]
Hi,
I get an error right after starting the container. I think the JDownload.rar file should be downloaded with can curl call at first.
In my log it fails with exit code 28.

It could be blocked by my pihole, but I am not able to find an entry inside the pihole query log. where the container or host trys to reach a domain.

Any Ideas?
Thanx

1970-02-28T03:34:19+00:00| ________________________________________ CONTAINER STARTED _________________________________________
,1970-02-22T20:08:27+00:00| WARNING Environment variables 'UID' and 'GID' are no longer used. Please use the '--user' docker parameter (https://github.com/antlafarge/jdownloader#docker-run).
,1970-02-24T08:32:59+00:00| Download JDownloader.jar
,1970-02-22T20:08:27+00:00| FATAL ERROR JDownloader.jar download failed: curl exited with code '28'
,1970-03-01T15:58:51+00:00| Get more informations here : https://github.com/antlafarge/jdownloader#troubleshooting
,1970-02-23T14:20:43+00:00| _________________________________________ CONTAINER EXITED _________________________________________

**Comment by antlafarge** [comment]
Hello,

Did you run the container on an armhf (arm 32 bits) OS?
If yes, this error  can occur because of docker problems on that platform, and the workaround is to use the `privileged` flag : https://github.com/antlafarge/jdownloader#troubleshooting

**Comment by RdTrxx** [comment]
Hey,

Yes, I do.
That was pretty easy, now it works.
Sorry, I did not read that hint.

Thanx for your work!

**Comment by antlafarge** [comment]
You're welcome. Thank you. Have fun! =]

**Comment by the4anoni** [comment]
> Hello,
> 
> Did you run the container on an armhf (arm 32 bits) OS?
> If yes, this error can occur because of docker problems on that platform, and the workaround is to use the `privileged` flag : https://github.com/antlafarge/jdownloader#troubleshooting

Are you working on fix to this?

The problem with this solution is now JDownloader saves configs, etc as root, and I can't edit them via my standard user account.
Also this is security risk.

**Comment by antlafarge** [comment]
Sorry about that but I can't fix anything, that's a docker issue. It should work without this flag. The only thing you can do is to report the problem to the docker team; to hope this issue to be fixed; and to retry sometimes by removing the privileged flag to see what is going on...

**Comment by the4anoni** [comment]
Looks like I've fixed issue!

Maybe this helped, idk.
https://docs.linuxserver.io/faq#libseccomp

Anyway it works without privilaged mode on armhf Raspbian Lite!

**Comment by antlafarge** [comment]
Hello, thank you for this information, what OS do you run?  
And did the soution 1, 2 or 3 worked for you?

**Comment by the4anoni** [comment]
> Hello, thank you for this information, what OS do you run? And did the soution 1, 2 or 3 worked for you?

Raspberry Pi OS ArmHF (Raspbian).
Option 2 worked for me, but 1 should work too.
