### ISSUE TITLE
[Odroid HC1 / Armbian arm/v7 / Ubuntu image] su: Authentication failure

### ISSUE THREAD

**Issue by kthxbai0815** [antlafarge/jdownloader#2]
Hey there!

My jd2 container won't start. Some informations you might need for solving this issue:

1970-02-19T04:31:55+00:00| ===== CONTAINER STARTED =====
1970-02-25T20:57:31+00:00| Setting up User and Group
1970-02-28T12:40:27+00:00| Create user 'jduser' (UID '1000') with primary group 'jdgroup' (GID '1000')
1970-02-24T08:32:59+00:00| User and group set up
1970-02-25T02:45:15+00:00| User 'jduser' and group 'jdgroup' selected
1970-03-02T01:04:59+00:00| ----------------------------------------
1970-02-21T08:52:11+00:00| Setting up JDownloader
1970-02-24T00:35:07+00:00| Replacing JDownloader email in myJDownloader settings file
1970-02-23T10:55:55+00:00| Replacing JDownloader password in myJDownloader settings file
1970-02-28T03:34:19+00:00| Replacing JDownloader devicename in myJDownloader settings file
1970-03-01T08:00:59+00:00| JDownloader set up
1970-02-21T19:06:35+00:00| ----------------------------------------
1970-02-24T07:24:43+00:00| Downloading JDownloader.jar
1970-02-20T14:39:55+00:00| JDownloader.jar downloaded
1970-03-02T12:27:39+00:00| Setup access rights to current directory
1970-03-02T02:13:15+00:00| ----------------------------------------
1970-02-27T10:30:19+00:00| Starting JDownloader
su: Authentication failure
1970-03-02T02:13:15+00:00| JDownloader stopped
1970-02-19T07:56:43+00:00| ===== CONTAINER STOPPED =====

kthxbai@odroid:~ $ id kthxbai
uid=1000(kthxbai) gid=1000(kthxbai) groups=1000(kthxbai),20(dialout),27(sudo),29(audio),44(video),46(plugdev),101(systemd-journal),106(input),108(netdev),110(ssh),114(sambashare),115(minidlna),117(bluetooth),998(docker)

Host Details:
Hostname	odroid
OS Information	linux armv7l Armbian 21.05.2 Buster
Kernel Version	4.14.150-odroidxu4
Total CPU	8
Total memory	2.1 GB
 Engine Details
Version	19.03.13 (API: 1.40)
Root directory	/mnt/extdsk/docker
Storage Driver	overlay2
Logging Driver	json-file
Volume Plugins	local
Network Plugins	bridge, host, ipvlan, macvlan, null, overlay

antlafarge/jdownloader:latest
Size	392 MB
Created	2021-05-20 14:55:18
Build	Docker on linux, arm

services:
  jdownloader:
    image: antlafarge/jdownloader:latest
    container_name: jdownloader2
    restart: on-failure
    volumes:
      - "/mnt/extdsk/docker_download/jd2:/jdownloader/downloads"
      - "/mnt/extdsk/docker_download/jd2/logs:/jdownloader/logs"
      - "/mnt/extdsk/docker_download/jd2/cfg:/jdownloader/cfg"
    environment:
      - "JD_EMAIL=max@mustermann.de"
      - "JD_PASSWORD=123456789"
      - "JD_NAME=jdownloader2@odroid"
      - "UID=1000"
      - "GID=1000"

**Comment by antlafarge** [comment]
Are you sure you started the container with the administration permissions?

Verify your user is in the `docker` group, or you started the container with sudo or as root user).

**Comment by antlafarge** [comment]
Hello, thank you for reporting this issue.

I don't see any easy fix for now. We need to investigate further.
I see your dates are broken too.

I only have a raspberry pi 3, so I will not be able to debug this image for your device, because I believe Armbian is not compatible with Raspberry pi devices.
Are you a developer? If so, you can debug and do the fixes and submit a pull request.
It not, maybe you can contact me by email to see if you can let me access your device remotely to debug the image?

**Comment by kthxbai0815** [comment]
Hi,

I also noticed the broken dates, it seems like there is a problem when logging to JSON format.
Similar topic: https://github.com/rancher/rancher/issues/25318

Nope, i'm not a developer, i'm just an ordinary user with some administration experience and background.
Running the container with sudo also does not work, same error. Found your address, I'll send you a mail.

**Comment by antlafarge** [comment]
This date issue is not related to JSON format. I don't use JSON to log. There should be a problem with this bash command on Armbian OS : `date -I'seconds'` (https://github.com/antlafarge/jdownloader/blob/581b71a1f42fdcda1c80cabfdb12e6d9119f28ee/functions.sh#L8).

Okay thank you

**Comment by antlafarge** [comment]
Ok so the bug might be related to a problem with docker on armhf architectures. Adding `--privileged` flag in docker CLI or docker-compose.yml can resolve the problem.

**Comment by kthxbai0815** [comment]
For me it seems like it's really necessary to use the (scary) "--privileged" flag, otherwise the container won't start:

ERROR JDownloader.jar download failed: curl returned code '28'

I played around with the fine grain controls over the capabilities using "--cap-add", in hope being able to start the container without granting to much privileges, but I was not successful. Even with "--cap-add=ALL" I still get error code '28.'

**Comment by antlafarge** [comment]
Oh yeah if you encounter the same difficulties to run the container by using `--cap-add`, that means we can't really do better.
I have the same problem on raspberry OS arm/v7, I have to use the `--privileged` flag too.
Thank you for your feedback.
The most important thing is that you are now able to use jdownloader on your Odroid HC1 :)

**Comment by antlafarge** [comment]
I close the issue, you can continue to share informations if you want

**Comment by antlafarge** [comment]
I close the issue, you can continue to share informations if you want
