### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by hackmonker** [antlafarge/jdownloader#22]
Was facing a bit problem regarding the downloads permissions. all the downloaded files seem to be having root:root permissions. any way we can use my user for it? I tried setting puid and guid but it still gives the downloaded files root ownership. is it not possible or am I missing something?

**Comment by antlafarge** [comment]
Hello, you should give ownership on these folders to your user. If you let Docker create these directories for you. The root will have the ownership (as user and as group) on these directories.
Look at chown command :)

**Comment by domi-a** [comment]
> Hello, you should give ownership on these folders to your user. If you let Docker create these directories for you, the root will have the ownership (as user and as group) on these directories. Look at chown command. And check the uid and gid are correct :)

i was facing the same issue. this works for me.
had to set rights of the `_data` folder in the generated config volume and the `downloads` folder to my user along with `    user:1000:100 ` on raspberry-os

**Comment by antlafarge** [comment]
Thank you for this information, I will add this information in the README to clarify this step.

**Comment by domi-a** [comment]
> https://github.com/antlafarge/jdownloader/commit/04fba1cf81bda9f0524e7f4d10dd09562c5dc614

you can even do it with volumes created by docker or docker-compose. 
- it will fail at first start after volume creating because of the root rights in the config volume
- but then i changed the permissions of the _data folder in the created config volume 
- restartet the container and it worked like a charm.

**Comment by antlafarge** [comment]
> 

For sure, but having a process where a failure is part of the process is not a great idea by my opinion. So I prefer to explain to users they need to create the folder before.
