### ISSUE TITLE
Errors of caracters on README.md

### ISSUE THREAD

**Issue by pabloalcantara** [antlafarge/jdownloader#24]
Just a simple thing, on the parameters table, you´re using "-" on the itens, but the it´s "_":
Ex:
"\<JD-EMAIL\> --> \<JD_EMAIL\>"

**Comment by antlafarge** [comment]
Hello, It was intended because that's se name of the parameter on the example, not the name of the environment variable, but to avoid any ambiguity, I modified like you proposed. Thank you.

**Comment by pabloalcantara** [comment]
Thanks
