### ISSUE TITLE
FATAL ERROR JDownloader.jar download failed: curl exited with code '6'

### ISSUE THREAD

**Issue by andreascschmidt** [antlafarge/jdownloader#26]
Restarted my JD2, and it doesn't start any more with the following error. 

Delete any existing JDownloader installation files
Download JDownloader.jar
FATAL ERROR JDownloader.jar download failed: curl exited with code '6'
Get more informations here : https://github.com/antlafarge/jdownloader#troubleshooting

This is reproduceable on another fresh install system. 

However, cURL Error 6 is a Could not resolve host, so I'm not sure where It's trying to download.

**Comment by antlafarge** [comment]
Hello, someone got the same erreur several months ago, it was a dns resolution problem on his system. Look at this and let me know if you can't resolve this?
[issue dns](https://github.com/antlafarge/jdownloader/issues/25#issuecomment-1241202383)

**Comment by andreascschmidt** [comment]
Would you have the URL its trying to get the .jar from for me please? 
I don't have any pihole and there was no change on my network or DNS in the last weeks. Maybe the source is dead.

**Comment by antlafarge** [comment]
Yes you can find it here : https://github.com/antlafarge/jdownloader/blob/main/docker-entrypoint.sh#L62
The url is http://installer.jdownloader.org/JDownloader.jar
It works for me

**Comment by antlafarge** [comment]
Commands for testing on a fresh ubuntu image :
```bash
docker run -it ubuntu bash

apt-get update

apt-get install -y --no-install-recommends curl

curl -vO "http://installer.jdownloader.org/JDownloader.jar"

ls -lh "JDownloader.jar"
```
The file should be around 4M/5M

**Comment by antlafarge** [comment]
Commands for testing on `antlafarge/jdownloader` image :
```bash
docker run -it antlafarge/jdownloader bash

curl -vO "http://installer.jdownloader.org/JDownloader.jar"

ls -lh "JDownloader.jar"
```
