### ISSUE TITLE
Fatal Error during Download

### ISSUE THREAD

**Issue by faro2023** [antlafarge/jdownloader#36]
After the Update to the latest version from 18.09.2023 i got the following error:

```
2023-09-20T16:18:42+00:00| ________________________________________ CONTAINER STARTED _________________________________________
2023-09-20T16:18:42+00:00| OS = "Ubuntu 22.04.3 LTS"
./docker-entrypoint.sh: line 37: ii: command not found
./docker-entrypoint.sh: line 37: ii: command not found
2023-09-20T16:18:42+00:00| JAVA version = " "
2023-09-20T16:18:42+00:00| JAVA options = ""
2023-09-20T16:18:42+00:00| Delete any existing JDownloader installation files
2023-09-20T16:18:42+00:00| Download https://installer.jdownloader.org/JDownloader.jar
2023-09-20T16:18:58+00:00| JDownloader.jar download failed: curl exited with code '6'
2023-09-20T16:18:58+00:00| Download http://installer.jdownloader.org/JDownloader.jar
2023-09-20T16:19:14+00:00| FATAL ERROR JDownloader.jar download failed: curl exited with code '6'
2023-09-20T16:19:14+00:00| Get more informations here : https://github.com/antlafarge/jdownloader#troubleshooting
2023-09-20T16:19:14+00:00| ________________________________________ CONTAINER EXITED __________________________________________
```

**Comment by antlafarge** [comment]
Hello did you solved the problem?

**Comment by faro2023** [comment]
Partial. I tried it on another Docker host, no problems here. Where the problems occur, I was able to remedy the situation by setting the network mode to host. In bridge mode it can not download the jdownloader.jar. I don't understand why. Other containers on the same host can access the internet in bridge mode without problems.
I have completely removed the container and rebuilt it, always without success. only the network host mode works.

**Comment by antlafarge** [comment]
Maybe you have some privileges issues with this docker host? Maybe try the `--privileged` flag ? https://github.com/antlafarge/jdownloader#docker-privileges

**Comment by faro2023** [comment]
its not an arm, its an i5 proxmox host with vm ubuntu 22.xx -> docker -> jdown

the privileged  mode doesnt work. only the network host mode works for the moment

**Comment by antlafarge** [comment]
Okay maybe a bug with this docker version

**Comment by antlafarge** [comment]
Or maybe a bug with m'y new release i will do some checks this night

**Comment by antlafarge** [comment]
Can you try the alpine version to test if it works?

**Comment by antlafarge** [comment]
I just want to notice I just fixed the logs with a new release

**Comment by faro2023** [comment]
> It Can be a bug with this docker version, or maybe a bug with my new release, i will do some checks this night.
> 
> Can you try the alpine version to test if it works?

i try, but the same result, i pull the new releases, same error with latest and alpine.
what i say, it works on this docker host until 1 wekk. my watchtower pull an update last week after this i have to use the netwprk host mode to run

**Comment by antlafarge** [comment]
I didn't change anything in network.
Maybe a bug in this docker host or in the lastest alpine and ubuntu images I use to build this new releases?

**Comment by antlafarge** [comment]
You can check at this
https://www.getfishtank.com/blog/resolve-curl-6-could-not-resolve-host-aka-ms-error

**Comment by faro2023** [comment]
first again many thanks to your support. i can't understand it yet, but i have redone the whole configuration of the docker with regard to ip and dns. now it works. what i don't understand is why the network host mode worked. i have in another docker pihole with unbound running, that also works great. only as soon as container wanted to access "internally" i.e. jdown -> pihole it came to problems. a reconfiguration helped. although in the end the settings are the same. it's currently inexplicable to me. have in any case many thanks

**Comment by antlafarge** [comment]
Okay no problem thank you for participating and have fun ;)
