### ISSUE TITLE
./setup.sh: line 52: ./cfg/org.jdownloader.settings.GeneralSettings.json: Permission denied

### ISSUE THREAD

**Issue by KiritoKunD2** [antlafarge/jdownloader#38]
When I try to perform the installation of the container, always show me permission denied.

sudo docker-compose up
[sudo] password for user:
Creating network "jdownloader2_default" with the default driver
Creating jdownloader2 ... done
Attaching to jdownloader2
jdownloader2   | 2023-12-14T02:58:44+00:00| CONTAINER STARTED 
jdownloader2   | 2023-12-14T02:58:44+00:00| OS = "Alpine Linux v3.18"
jdownloader2   | 2023-12-14T02:58:45+00:00| JAVA version = "openjdk17-jre-headless-17.0.8_p7-r0"
jdownloader2   | 2023-12-14T02:58:45+00:00| JAVA options = ""
jdownloader2   | 2023-12-14T02:58:45+00:00| Delete any existing JDownloader installation files
jdownloader2   | 2023-12-14T02:58:45+00:00| Download https://installer.jdownloader.org/JDownloader.jar
jdownloader2   | 2023-12-14T02:58:45+00:00| Write JDownloader download path in settings file
jdownloader2   | ./setup.sh: line 52: ./cfg/org.jdownloader.settings.GeneralSettings.json: Permission denied
jdownloader2   | 2023-12-14T02:58:45+00:00| ERROR printf exited with code '1'
jdownloader2   | 2023-12-14T02:58:45+00:00| FATAL ERROR setup.sh exited with code '1'
jdownloader2   | 2023-12-14T02:58:45+00:00| Get more informations here : https://github.com/antlafarge/jdownloader#troubleshooting
jdownloader2   | 2023-12-14T02:58:45+00:00| CONTAINER EXITED 
jdownloader2   | 2023-12-14T02:58:46+00:00| JAVA version = "openjdk17-jre-headless-17.0.8_p7-r0"
jdownloader2   | 2023-12-14T02:58:46+00:00| JAVA options = ""
jdownloader2   | 2023-12-14T02:58:46+00:00| Write JDownloader download path in settings file
jdownloader2   | ./setup.sh: line 52: ./cfg/org.jdownloader.settings.GeneralSettings.json: Permission denied
jdownloader2   | 2023-12-14T02:58:46+00:00| ERROR printf exited with code '1'
jdownloader2   | 2023-12-14T02:58:46+00:00| FATAL ERROR setup.sh exited with code '1'
jdownloader2   | 2023-12-14T02:58:46+00:00| Get more informations here : https://github.com/antlafarge/jdownloader#troubleshooting
jdownloader2   | 2023-12-14T02:58:46+00:00|  CONTAINER EXITED 
jdownloader2 exited with code 1
jdownloader2   | 2023-12-14T02:58:47+00:00| JAVA version = "openjdk17-jre-headless-17.0.8_p7-r0"
jdownloader2   | 2023-12-14T02:58:47+00:00| JAVA options = ""
jdownloader2   | 2023-12-14T02:58:47+00:00| Write JDownloader download path in settings file
jdownloader2   | ./setup.sh: line 52: ./cfg/org.jdownloader.settings.GeneralSettings.json: Permission denied
jdownloader2   | 2023-12-14T02:58:47+00:00| ERROR printf exited with code '1'
jdownloader2   | 2023-12-14T02:58:47+00:00| FATAL ERROR setup.sh exited with code '1'
jdownloader2   | 2023-12-14T02:58:47+00:00| Get more informations here : https://github.com/antlafarge/jdownloader#troubleshooting
jdownloader2   | 2023-12-14T02:58:47+00:00| CONTAINER EXITED 
jdownloader2 exited with code 1

**Comment by KiritoKunD2** [comment]
If I run the container as root, it works, but the files downloaded have root permissions and that is not what I want

**Comment by antlafarge** [comment]
Hello, I think you don't have any write right permissions on the directory `./cfg/org.jdownloader.settings.GeneralSettings.json`.
I recommand to redo the setup steps by being careful on the use of chmod and chown commands :
https://github.com/antlafarge/jdownloader#setup

**Comment by antlafarge** [comment]
Hello, I think you have write permission issues on the `config` directory on your host machine.
I recommand to re-do the setup steps and use `chmod` and `chown` commands to have write permissions and be the owner on the `downloads` and `config` directories.
Steps here : https://github.com/antlafarge/jdownloader#setup
Don't miss the step "Do the same for the config directory".
At the end of the configuration, your user should be the "user owner" and the "group owner" of these directories (or the group `users` (gid `100`) can be the "group owner").
And your right permissions should be something like `770` (`drwxrwx---`).
