### ISSUE TITLE
[Request] Umask env variable

### ISSUE THREAD

**Issue by amenolo** [antlafarge/jdownloader#40]
There's a way to set custom permission mask? Thanks!

**Comment by antlafarge** [comment]
Hello, can you explain what you want to achieve? :)

**Comment by amenolo** [comment]
Given that my JD2 instance is sharing download dir with a Nextcloud instance (based on Apache therefore running under www-data user), in my scenario would come in handy to be able to modify the default umask in order to avoid permission issues and recurrent manual changes in case of moving/deleting/renaming files and subdirs :relaxed:

**Comment by antlafarge** [comment]
I added a UMASK env variable, can you check if my change can meet your needs?
[348619cd15b174f5edcabe7672ee97e1041fbe5d](https://github.com/antlafarge/jdownloader/commit/348619cd15b174f5edcabe7672ee97e1041fbe5d)
I wait for your answer before deploying it on docker hub

**Comment by amenolo** [comment]
TBH I'm not that familiar with dockerfile syntax, anyway from what I understand it's seems OK to me.

**Comment by antlafarge** [comment]
I built a test image. Can you test it and let me now if it works?  
Image name and tag is `antlafarge/jdownloader:1.1-dev-alpine`.

**Comment by amenolo** [comment]
Just tested: works like a charm! 💯

**Comment by amenolo** [comment]
Please drop a messagge when final releases will be ready, thanks!

**Comment by antlafarge** [comment]
For sure, that's why I have not closed the issue for now :)

**Comment by antlafarge** [comment]
I rebuilt everything !

**Comment by amenolo** [comment]
Everything works properly, hope tiny additional feature will come in handy to someone else! 👍

**Comment by antlafarge** [comment]
Yes fore sure thank you for the request. Have fun !
