### ISSUE TITLE
docker repo missing

### ISSUE THREAD

**Issue by steled** [antlafarge/jdownloader#41]
Hi,

it seems that your Docker repo is completely missing.
Is this intended or maybe done by Docker?

BR

**Comment by antlafarge** [comment]
Hello, yes i don't know what happened. If my account has been hacked or suspended by docker?
I m unvestigating, and I contacted docker hub to know what is the problem?

**Comment by antlafarge** [comment]
It has been resolved. They said it should be a user request. So I Guess a bug or a hack. Anyway everything should be restored ! Thank you for the message !

**Comment by steled** [comment]
Hi,

good to hear, then I can remove my fork again 😄.
Just a note, I'm not sure how you build the images, but for the short term I've implemented the whole process via GitHub Actions if you want to use it too: [build.yml](https://github.com/steled/jdownloader/blob/main/.github/workflows/build.yml)

**Comment by antlafarge** [comment]
Okay thank you I build everything manually by using buildx, but I will look at this, thanks !

**Comment by kibashlive** [comment]
It's gone again.

**Comment by antlafarge** [comment]
Hello, thats not the same problem.
There is a bug with the "General" page of the repository on dockerhub.
The other tabs work.
I contacted the support team, i'm waiting for an answer.

Anyway you Can check the releases and the tags here :
https://hub.docker.com/repository/docker/antlafarge/jdownloader/tags

And you Can see the updated readme here : 
https://github.com/antlafarge/jdownloader/blob/main/README.md

**Comment by kibashlive** [comment]
Thanks for the fast reply. You're right https://hub.docker.com/r/antlafarge/jdownloader/tags does indeed work. Dockerhub should fix there error pages.

**Comment by antlafarge** [comment]
> Hi,
> 
> good to hear, then I can remove my fork again 😄. Just a note, I'm not sure how you build the images, but for the short term I've implemented the whole process via GitHub Actions if you want to use it too: [build.yml](https://github.com/steled/jdownloader/blob/main/.github/workflows/build.yml)

Hello, thank you I automatised the build and got inspired by your build script 😃
