### ISSUE TITLE
[FEATURE REQUEST] Support for docker compose secrets

### ISSUE THREAD

**Issue by bwalocha** [antlafarge/jdownloader#42]
Hi, thanks for sharing the source code!

I would like to ask if you are planning to support docker compose secrets (https://docs.docker.com/compose/use-secrets/)?

Now we can specify sensitive data using the following env. vars:
```
JD_EMAIL
JD_PASSWORD
JD_DEVICENAME
```

Would be nice to support also:
```
JD_EMAIL_FILE
JD_PASSWORD_FILE
JD_DEVICENAME_FILE
```

Thanks!

**Comment by antlafarge** [comment]
Hello, that's a nice idea. I will add this ! ;)

**Comment by antlafarge** [comment]
I pushed a dev version to test the feature. If you want to make a try, you can try one of these tags : 
- dev-alpine-openjdk17
- dev-ubuntu-openjdk17

**Comment by antlafarge** [comment]
The official tag images have been updated.
New docker images have been pushed.
Let me know if you encounter any issue.

**Comment by bwalocha** [comment]
You are AWESOME!!! 

I will check it in next days and let you know in case of any issue.
Thanks!
