### ISSUE TITLE
Secrets stopped working recently for JD_DEVICENAME

### ISSUE THREAD

**Issue by cavalli1021w** [antlafarge/jdownloader#44]
Hi,

Relatively new to Docker and your JD2 container was the first I used.  Worked great for three months and still does today with one exception.  I use the "secrets" concept so that I don't have to include my email and password in my docoker-compose.yml file, but in local files.  Those two secrets work great.  The JD_DEVICENAME however used to work fine, but now seems to have a random 12 character name.  Looks hexidecimal and I initially thought it was my NIC address for the machine.

Anyway, it used to work fine and has now been failing that DEVICENAME for the past 3 weeks or so.  Any help appreciated.  Thanks!

Here's the code from the docker-compose.yml file:

`---
# https://hub.docker.com/r/antlafarge/jdownloader
# https://github.com/antlafarge/jdownloader
services:
  jdownloader:
    image: antlafarge/jdownloader:latest
    container_name: jdownloader                       # optional
    user: 1021:1021                                   # optional
    volumes:
      - '/home/${USER}/Docker/config/jdownloader/:/jdownloader/cfg/' # optional
      - "/home/${USER}/zDL/JDownloader/:/jdownloader/downloads/"
    secrets:
      - JD_EMAIL
      - JD_PASSWORD
      - JD_DEVICENAME
    ports:
      - "3129:3129" # optional
    labels:
      - "diun.enable=true"                                 # Enable Diun
    restart: on-failure:5 # optional
    #restart: unless-stopped

secrets:
  JD_EMAIL:
    file: "./JD_EMAIL"
  JD_PASSWORD:
    file: "./JD_PASSWORD"
  JD_DEVICENAME:
    file: "./JD_DEVICENAME"
`

**Comment by antlafarge** [comment]
Hello,
I reverted the jd devicename as a secret because there is no reason this information to be a secret.
Sorry I forgot to update the readme of this repo and on dockerhub after this change. This is done.
You can setup this information with the environment variable `JD_DEVICENAME`.
```yml
    environment:
      - "JD_DEVICENAME=JDownloader" # optional
```
Thank you for letting me know this problem ! This is fixed !
Have fun ! :)

**Comment by cavalli1021w** [comment]
If I understand right, you've taken away the ability to use it as an external file?  I preferred it that way, primarily because I maintain multiple servers that use this docker container.  So if/when I want to maintain the compose file and/or changes/updates to it, the same docker-compose.yml file can be copied to all with a local JD_DEVICENAME file to differentiate.  If this is a permanent change, then I will have to go to each machine and install the "environment:" section as you stated and have different files for each machine.  Old way preferred, if both can be available.  If not, is what it is, and will update all containers appropriately.  Either way, thanks for the great container!  :D

**Comment by antlafarge** [comment]
Okay that's a relevant remark I didn't think. So I will revert to re-enable this jd devicename secret file.
Thank you for your remark, and happy you found this project useful ;)

**Comment by cavalli1021w** [comment]
Thanks!  And again, your work is greatly appreciated.  My switch to Docker was so easy to learn/enact with containers like this.  Take care.

**Comment by antlafarge** [comment]
That's done, you can now re-pull the images :)

**Comment by cavalli1021w** [comment]
Don't know if anyone else having problems, but old version was working an hour ago and immediately exits on all machines upon start up with same config file.  Didn't want to open a new ticket, becuase I don't really have any additional information other than updated the image / restarted.  Thanks.

**Comment by antlafarge** [comment]
I tried the new `ubuntu-openjdk21` (`latest`) and `alpine-openjdk21` and everything works well by my side.
Can you share logs and docker compose to see what's happening?

**Comment by cavalli1021w** [comment]
Literally same docker-compose.yml shown in the first post of this thread.  As I stated, I'm relatively new to Docker, so not sure where to get "logs", unless you mean the logs that are in your container (which I haven't used).  It does seem to shut down immediately though.  On the two main servers, I use Debian/bookworm and another uses RaspbianOS/bookworm, if that makes a difference.  Will reseach "logs" for you on Google now.

**Comment by cavalli1021w** [comment]
Ah, easier to find logs than I thought it would be.  No idea what this means, but hopefully I've found something of use to you:

$ docker container logs jdownloader
/bin/bash: ./docker-entrypoint.sh: Permission denied
/bin/bash: ./docker-entrypoint.sh: Permission denied
/bin/bash: ./docker-entrypoint.sh: Permission denied
/bin/bash: ./docker-entrypoint.sh: Permission denied
/bin/bash: ./docker-entrypoint.sh: Permission denied
/bin/bash: ./docker-entrypoint.sh: Permission denied

**Comment by antlafarge** [comment]
Okay I changed the access permission of files inside the container from 777 to 775.
And the files are owned by root:root by default. I changed it to be 1000:100.

Anyway, if you don't use `user` parameter, you start the container as `root` and everything should be OK.
If you use `user`, and for example you use `1001:1001`, it should works because 775 means others can read and execute these files.
What is your user? (uid/gid)
Can you check your user can access files with access permissions 775 ?

**Comment by cavalli1021w** [comment]
$ id
uid=1021(cavalli) gid=1021(cavalli) groups=1021(cavalli),27(sudo),100(users),997 (docker)

Not sure about "Can you check your user can execute files with access permissions 771 ?"
If I understand right, "probably".  :D  Here's what I did.
I created a script called ytest which has the "ls" command inside of it.
I then said:
$ chmod 771 ytest
$ ./ytest
ran a perfect ls command, so I think yes?  :D  

Did this answer your questions correctly?

**Comment by antlafarge** [comment]
Yes thank you, I managed to reproduce the bug by my side. I'm working on a fix. Thank you!

**Comment by antlafarge** [comment]
I pushed new images. You can try.

**Comment by cavalli1021w** [comment]
Back up and running.  No idea how so much changed but glad you fixed it!  Thanks again for everything.

**Comment by antlafarge** [comment]
Yes It's my fault, that was a bad patch but everything's good now :)
Thank you to be patient !
